spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      comment-prefix: '#'
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadsInheritContextClassLoaderOfInitializingThread: true
          scheduler:
            instanceName: DatabaseClusteredScheduler
            instanceId: AUTO
            jmx:
              export: true
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true






